VERSION=1.1.0

BE_NAME=plex-medical-backend

AWS_REGION=eu-west-1
AWS_PROFILE=default

BE_TAG=${BE_NAME}:${VERSION}

ENVIRONMENT_NAME=live


BE_STACK_NAME=${BE_NAME}-${ENVIRONMENT_NAME}
CONTAINER_ID_BE=${BE_NAME}:${VERSION}

HEALTH_CHECK_PATH=/

ECR_REPO_BE_URL=150379301580.dkr.ecr.eu-south-1.amazonaws.com
ECR_REPO_BE_NAME=plex-medical-backend


